# config.mk - Generated by configure on Fri 16 Jan 2026 09:45:22 PM MST
# Do not edit manually - re-run ./configure to regenerate

# Application metadata
APP_NAME = pickleball-editor
APP_VERSION = 0.1.0

# Installation paths
PREFIX = /usr/local
BINDIR = $(PREFIX)/bin
DATADIR = $(PREFIX)/share
DESKTOPDIR = $(DATADIR)/applications

# Python configuration
PYTHON = .venv/bin/python
PYTHON_VERSION = 3.13.11
USE_VENV = yes
VENV_DIR = .venv

# System dependencies
MPV_VERSION = 2.5.0
FFMPEG_VERSION = n8.0.1
FFPROBE_VERSION = n8.0.1
QT6_VERSION = 6.10.1

# Build configuration
ENABLE_DEV = yes
PYINSTALLER = .venv/bin/pyinstaller

# Source paths
SRC_DIR = src
TESTS_DIR = tests
RESOURCES_DIR = resources

# Build output
BUILD_DIR = build
DIST_DIR = dist
SPEC_FILE = pickleball-editor.spec

# Test configuration
PYTEST = .venv/bin/pytest
RUFF = .venv/bin/ruff
MYPY = .venv/bin/mypy
BLACK = .venv/bin/black
