# Makefile for Pickleball Video Editor
# Requires: config.mk (generated by ./configure)

# Include configuration if it exists
-include config.mk

# -----------------------------------------------------------------------------
# Fallback Defaults (if config.mk doesn't exist)
# -----------------------------------------------------------------------------
APP_NAME ?= pickleball-editor
ML_APP_NAME ?= rally-trainer
APP_VERSION ?= 0.1.0
PREFIX ?= /usr/local
BINDIR ?= $(PREFIX)/bin
DATADIR ?= $(PREFIX)/share
DESKTOPDIR ?= $(DATADIR)/applications

PYTHON ?= python3
PYINSTALLER ?= pyinstaller
PYTEST ?= pytest
RUFF ?= ruff
MYPY ?= mypy
BLACK ?= black

SRC_DIR ?= src
ML_DIR ?= ml
TESTS_DIR ?= tests
RESOURCES_DIR ?= resources
BUILD_DIR ?= build
DIST_DIR ?= dist
SPEC_FILE ?= $(APP_NAME).spec
ML_SPEC_FILE ?= $(ML_APP_NAME).spec

VENV_DIR ?= .venv
USE_VENV ?= yes

# -----------------------------------------------------------------------------
# Phony Targets
# -----------------------------------------------------------------------------
.PHONY: all build build-ml smoke-ml install install-ml uninstall uninstall-ml clean distclean test lint format run help check-config

# Default target
all: build

# -----------------------------------------------------------------------------
# Configuration Check
# -----------------------------------------------------------------------------
check-config:
	@if [ ! -f config.mk ]; then \
		echo "ERROR: config.mk not found. Please run ./configure first."; \
		echo ""; \
		echo "Example:"; \
		echo "  ./configure"; \
		echo "  make"; \
		exit 1; \
	fi

# -----------------------------------------------------------------------------
# Build Target
# -----------------------------------------------------------------------------
build: check-config
	@echo "==> Building $(APP_NAME) v$(APP_VERSION)..."
	@if [ "$(USE_VENV)" = "yes" ] && [ ! -f "$(VENV_DIR)/bin/activate" ]; then \
		echo "ERROR: Virtual environment not found at $(VENV_DIR)"; \
		echo "Please run ./configure to set up the environment."; \
		exit 1; \
	fi
	$(PYINSTALLER) --clean --noconfirm $(SPEC_FILE)
	@echo "✓ Build complete: $(DIST_DIR)/$(APP_NAME)"

# -----------------------------------------------------------------------------
# Install Target
# -----------------------------------------------------------------------------
# Application is installed as:
#   $(DATADIR)/$(APP_NAME)/     - Application files (directory bundle)
#   $(BINDIR)/$(APP_NAME)       - Symlink to the executable
#   $(DESKTOPDIR)/$(APP_NAME).desktop - Desktop entry (optional)
# -----------------------------------------------------------------------------
install: check-config build
	@echo "==> Installing $(APP_NAME) to $(DESTDIR)$(PREFIX)..."
	@# Install application bundle to share directory
	install -d $(DESTDIR)$(DATADIR)/$(APP_NAME)
	cp -r $(DIST_DIR)/$(APP_NAME)/* $(DESTDIR)$(DATADIR)/$(APP_NAME)/
	chmod 755 $(DESTDIR)$(DATADIR)/$(APP_NAME)/$(APP_NAME)
	@# Create symlink in bin directory
	install -d $(DESTDIR)$(BINDIR)
	ln -sf $(DATADIR)/$(APP_NAME)/$(APP_NAME) $(DESTDIR)$(BINDIR)/$(APP_NAME)
	@# Install desktop entry if available
	@if [ -f "$(APP_NAME).desktop" ]; then \
		echo "==> Installing desktop entry..."; \
		install -d $(DESTDIR)$(DESKTOPDIR); \
		install -m 644 $(APP_NAME).desktop $(DESTDIR)$(DESKTOPDIR)/$(APP_NAME).desktop; \
	fi
	@echo "✓ Installation complete"
	@echo ""
	@echo "Application installed to: $(DESTDIR)$(DATADIR)/$(APP_NAME)/"
	@echo "Run with: $(APP_NAME)"

# -----------------------------------------------------------------------------
# ML Build Target
# -----------------------------------------------------------------------------
build-ml: check-config
	@echo "==> Building $(ML_APP_NAME) v$(APP_VERSION)..."
	@if [ "$(USE_VENV)" = "yes" ] && [ ! -f "$(VENV_DIR)/bin/activate" ]; then \
		echo "ERROR: Virtual environment not found at $(VENV_DIR)"; \
		echo "Please run ./configure --enable-ml to set up the environment."; \
		exit 1; \
	fi
	@$(VENV_DIR)/bin/python -c "import torch" 2>/dev/null || { \
		echo "ERROR: PyTorch not installed. Run: ./configure --enable-ml"; \
		exit 1; \
	}
	$(PYINSTALLER) --clean --noconfirm $(ML_SPEC_FILE)
	@echo "==> Build complete: $(DIST_DIR)/$(ML_APP_NAME)"

# -----------------------------------------------------------------------------
# ML Bundle Smoke Test
# -----------------------------------------------------------------------------
smoke-ml:
	@echo "==> Running bundle smoke test on $(DIST_DIR)/$(ML_APP_NAME)..."
	@bash scripts/smoke_bundle.sh "$(DIST_DIR)/$(ML_APP_NAME)/$(ML_APP_NAME)"

# -----------------------------------------------------------------------------
# ML Install Target
# -----------------------------------------------------------------------------
install-ml: check-config build-ml
	@echo "==> Installing $(ML_APP_NAME) to $(DESTDIR)$(PREFIX)..."
	@# Install application bundle to share directory
	install -d $(DESTDIR)$(DATADIR)/$(ML_APP_NAME)
	cp -r $(DIST_DIR)/$(ML_APP_NAME)/* $(DESTDIR)$(DATADIR)/$(ML_APP_NAME)/
	chmod 755 $(DESTDIR)$(DATADIR)/$(ML_APP_NAME)/$(ML_APP_NAME)
	@# Create symlink in bin directory
	install -d $(DESTDIR)$(BINDIR)
	ln -sf $(DATADIR)/$(ML_APP_NAME)/$(ML_APP_NAME) $(DESTDIR)$(BINDIR)/$(ML_APP_NAME)
	@echo "==> Installation complete"
	@echo ""
	@echo "Application installed to: $(DESTDIR)$(DATADIR)/$(ML_APP_NAME)/"
	@echo "Run with: $(ML_APP_NAME) train --data-dir <path>"
	@echo "      or: $(ML_APP_NAME) predict --video <path>"

# -----------------------------------------------------------------------------
# Uninstall Targets
# -----------------------------------------------------------------------------
uninstall-ml:
	@echo "==> Uninstalling $(ML_APP_NAME) from $(DESTDIR)$(PREFIX)..."
	rm -f $(DESTDIR)$(BINDIR)/$(ML_APP_NAME)
	rm -rf $(DESTDIR)$(DATADIR)/$(ML_APP_NAME)
	@echo "==> Uninstall complete"

# -----------------------------------------------------------------------------
# Uninstall Target
# -----------------------------------------------------------------------------
uninstall:
	@echo "==> Uninstalling $(APP_NAME) from $(DESTDIR)$(PREFIX)..."
	rm -f $(DESTDIR)$(BINDIR)/$(APP_NAME)
	rm -rf $(DESTDIR)$(DATADIR)/$(APP_NAME)
	rm -f $(DESTDIR)$(DESKTOPDIR)/$(APP_NAME).desktop
	@echo "✓ Uninstall complete"

# -----------------------------------------------------------------------------
# Clean Targets
# -----------------------------------------------------------------------------
clean:
	@echo "==> Cleaning build artifacts..."
	rm -rf $(BUILD_DIR) $(DIST_DIR)
	find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete
	find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".mypy_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".ruff_cache" -exec rm -rf {} + 2>/dev/null || true
	@echo "✓ Clean complete"

distclean: clean
	@echo "==> Deep cleaning (including venv and config)..."
	rm -rf $(VENV_DIR)
	rm -f config.mk
	@echo "✓ Distclean complete"
	@echo ""
	@echo "Run ./configure to reconfigure the project."

# -----------------------------------------------------------------------------
# Test Targets
# -----------------------------------------------------------------------------
test: check-config
	@echo "==> Running tests with pytest..."
	@if [ "$(USE_VENV)" = "yes" ] && [ ! -f "$(VENV_DIR)/bin/activate" ]; then \
		echo "ERROR: Virtual environment not found. Run ./configure first."; \
		exit 1; \
	fi
	$(PYTEST) $(TESTS_DIR) -v

test-coverage: check-config
	@echo "==> Running tests with coverage..."
	$(PYTEST) $(TESTS_DIR) --cov=$(SRC_DIR) --cov-report=html --cov-report=term

# -----------------------------------------------------------------------------
# Lint and Format Targets
# -----------------------------------------------------------------------------
lint: check-config
	@echo "==> Running linters..."
	@echo "-> ruff check..."
	$(RUFF) check $(SRC_DIR) $(TESTS_DIR)
	@echo "-> mypy type checking..."
	$(MYPY) $(SRC_DIR)
	@echo "✓ Lint complete"

format: check-config
	@echo "==> Formatting code with black and ruff..."
	$(BLACK) $(SRC_DIR) $(TESTS_DIR)
	$(RUFF) check --fix $(SRC_DIR) $(TESTS_DIR)
	@echo "✓ Format complete"

# -----------------------------------------------------------------------------
# Development Run Target
# -----------------------------------------------------------------------------
run: check-config
	@echo "==> Running $(APP_NAME) in development mode..."
	@if [ "$(USE_VENV)" = "yes" ]; then \
		. $(VENV_DIR)/bin/activate && $(PYTHON) -m $(SRC_DIR).main; \
	else \
		$(PYTHON) -m $(SRC_DIR).main; \
	fi

# -----------------------------------------------------------------------------
# Help Target
# -----------------------------------------------------------------------------
help:
	@echo "Pickleball Video Editor - Build System"
	@echo ""
	@echo "Available targets:"
	@echo "  all/build        Build the editor executable with PyInstaller (default)"
	@echo "  build-ml         Build the rally-trainer ML executable"
	@echo "  install          Install editor to PREFIX/bin (use DESTDIR for staging)"
	@echo "  install-ml       Install rally-trainer to PREFIX/bin"
	@echo "  uninstall        Remove installed editor files"
	@echo "  uninstall-ml     Remove installed rally-trainer files"
	@echo "  clean            Remove build artifacts (__pycache__, dist/, build/)"
	@echo "  distclean        Deep clean including venv and config.mk"
	@echo "  test             Run pytest test suite"
	@echo "  test-coverage    Run tests with coverage report"
	@echo "  lint             Run ruff and mypy linters"
	@echo "  format           Format code with black and ruff"
	@echo "  run              Run the application in development mode"
	@echo "  help             Show this help message"
	@echo ""
	@echo "Configuration:"
	@echo "  PREFIX           Installation prefix (default: /usr/local)"
	@echo "  DESTDIR          Staging directory for packaging (default: empty)"
	@echo "  APP_NAME         Application name (from config.mk)"
	@echo "  APP_VERSION      Application version (from config.mk)"
	@echo ""
	@echo "Examples:"
	@echo "  ./configure && make             # Configure and build editor"
	@echo "  ./configure --enable-ml && make build-ml  # Build rally-trainer"
	@echo "  make test                        # Run tests"
	@echo "  sudo make install                # Install editor system-wide"
	@echo "  sudo make install-ml             # Install rally-trainer system-wide"
	@echo "  make install PREFIX=~/.local     # Install to user directory"
	@echo "  make DESTDIR=/tmp/pkg install    # Package to staging area"
	@echo "  make run                         # Run in development mode"
	@echo ""
	@echo "First time setup (editor):"
	@echo "  1. ./configure [OPTIONS]"
	@echo "  2. make"
	@echo "  3. make test"
	@echo "  4. sudo make install"
	@echo ""
	@echo "First time setup (ML rally-trainer):"
	@echo "  1. ./configure --enable-ml"
	@echo "  2. make build-ml"
	@echo "  3. sudo make install-ml"
	@echo ""
	@echo "See ./configure --help for configuration options."
